previewsEnabled: true
services:
  - type: static
    name: paytoday-namibian-loans
    buildCommand: "npm install && npm run build"
    publishDir: "dist"
    envVars:
      - key: NODE_VERSION
        value: "18"
